# TensorFlow Tutorial

In [2]:
import tensorflow as tf

## Constant, Graph, Session

In [3]:
a = tf.constant([5],dtype=tf.float32)
b = tf.constant([10],dtype=tf.float32)
c = tf.constant([2],dtype=tf.float32)

d = a*b+c

In [4]:
sess = tf.Session()
result = sess.run(d)
print (result)

[ 52.]


## Placeholder

In [5]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y,feed_dict={x:input_data})

print (result)

[  2.   4.   6.   8.  10.]


## Variable

In [7]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32)
y = W*x

sess = tf.Session()
# initialize_all_variables will be removed
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print (result)

[  2.   4.   6.   8.  10.]


## Array

In [8]:
x = tf.constant([ [1.0,2.0,3.0] ])
w = tf.constant([ [2.0],[2.0],[2.0] ])
y = tf.matmul(x,w)
print (x.get_shape())
print (w.get_shape())
print (y.get_shape())

(1, 3)
(3, 1)
(1, 1)


In [10]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)
print (result)

[[ 12.]]


In [11]:
x = tf.Variable([ [1.,2.,3.] ])
w = tf.Variable([ [2.],[2.],[2.]])
y = tf.matmul(x,w)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print (result)

[[ 12.]]


### Array with placeholder

In [12]:
input_data = [ [1.,2.,3.],[1.,2.,3.],[2.,3.,4.] ] #3x3 matrix
x = tf.placeholder(dtype=tf.float32,shape=[None,3]) #as the number of data may vary 
w = tf.Variable([ [2.],[2.],[2.] ], dtype = tf.float32) #3x1 matrix
y = tf.matmul(x,w)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print (result)

[[ 12.]
 [ 12.]
 [ 18.]]


#### Concept images
![concept image](http://cfile7.uf.tistory.com/image/271B824458609EC43109AF)
![concept image](http://cfile7.uf.tistory.com/image/214B164458609EC50BDD08)

## Broadcast

In [13]:
input_data = [
    [1,1,1],[2,2,2]
]
x = tf.placeholder(dtype=tf.float32,shape=[2,3])
w = tf.Variable([[2],[2],[2]],dtype=tf.float32)
b = tf.Variable([4],dtype=tf.float32)
y = tf.matmul(x,w)+b

print (x.get_shape())
print (w.get_shape())
print (b.get_shape())
print (y.get_shape())

(2, 3)
(3, 1)
(1,)
(2, 1)


In [14]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print (result)

[[ 10.]
 [ 16.]]


#### Concept images

![](http://cfile6.uf.tistory.com/image/2536044F5861E086211339)
![](http://cfile23.uf.tistory.com/image/263ADD4F5861E08B1E45AA)

## Rank of Array
![](http://cfile6.uf.tistory.com/image/2278874B5862600726E41F)

# References
* http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc
* http://bcho.tistory.com/1153